spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: ${BD_HOST:jdbc:mysql://127.0.0.1:3306/miniautorizador}
    username: root
    password:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

redis:
  host: ${REDIS_HOST:127.0.0.1}
  port: 6379